### ISSUE TITLE
Search parameters not serialized

### ISSUE THREAD

**Issue by rcdailey** [cpp-netlib/url#14] opened 2019-07-02 19:44 UTC
I build a URL the following way:

```cpp
skyr::url builder{"http://127.0.0.1:7720/path/to/endpoint"};
auto& params = builder.search_parameters();
params.append("caller", "one");
params.append("req", "two");
std::cout << skyr::serialize(builder.record()) << "\n";
```

It does not add the query parameters to the output. The way this API is used is really weird. I see a `skyr::url::set_search()`, which seems to be the intended way of doing this. But if I want to construct my query parameters piecemeal as I have above, it doesn't work because the `url_search_parameters` constructor does not initialize the optional `url_record::query` member unless it was already non-empty to begin with. I think that the constructor should initialize empty query member if it was obtained using a non-const reference (as is the case with `url::search_parameters()`). If you intended this to not mutate the parameters, please change the return value to `url_search_parameters const&`.

**Comment by rcdailey** [comment] 2019-07-02 19:59
Note that this does seem to work:

```cpp
skyr::url_search_parameters params;
params.append("caller", "one");
params.append("req", "two");

skyr::url builder{uri};
builder.set_search(params.to_string());

std::cout << skyr::serialize(builder.record()) << "\n";
```

But it's a bit silly because it boils down to:

1. Build a list of key value pairs for the parameters
2. Serialize that list of pairs into a string
3. Pass the string into the `url` object
4. Deserialize the string back into a list of pairs
5. Serialize the URL + list of pairs for the params back into a string

So it's very inefficient, we do a lot of boxing/unboxing repeatedly. My first method eliminates step 2 and 4, assuming you can make the `url` class make more use of the `parameters_` member for serialization purposes (maybe serialize the `parameters_` member into the `url_` member when `url::record()` is called?)

**Comment by glynos** [comment] 2019-07-03 18:36
What is the output of your first excerpt? For me, the output of both is:

```
http://127.0.0.1:7720/path/to/endpoint?caller=one&req=two
```

So I'm unable so far to reproduce your error.

I pushed some recent changes on master, can you test again?

**Comment by glynos** [comment] 2019-07-22 19:55
I can't reproduce this and I don't have a response, so I will close this issue.

**Closed by glynos** 2019-07-22 19:55 UTC
