### ISSUE TITLE
File URLs with port in hostname do not work

### ISSUE THREAD

**Issue by rcdailey** [cpp-netlib/url#12] opened 2019-06-25 17:33 UTC
This URL breaks the parser:

```
file://example.com:789/over/there?name=ferret#nose
```

It parses the hostname as `example.com:789`, but it should be `example.com` with a port of `789`.

In `url_parse.cpp`, seems to me like file URIs should use `url_parse_state::host`, and not have a specialized, less flexible parser for hostnames represented by `url_parse_state::file_host`. At the very least, the file URL hostname parsing should add support for `:`.

**Comment by glynos** [comment] 2019-06-30 13:11
Hi, I'm going to take a look at this soon. For your point on host/file_host, this comes from the processing sets defined in the [WhatWG URL spec](https://url.spec.whatwg.org/#file-host-state), so I think this is the intended behaviour. I'm going to double check that though.

**Comment by glynos** [comment] 2019-06-30 14:07
I just took a closer look, and I understand this to be standard-conforming. I have double checked with another WhatWG URL implementation (https://docs.rs/url/1.7.2/url/) which exhibits the same behaviour. Therefore, I'll close this issue.

**Closed by glynos** 2019-06-30 14:07 UTC
